# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ace14d84eeccbf67fd8951119532581f9501bc0d275e014a56a5e2c9da6b4ca1710265af7a31e35d4f05f20c7aa00c10159ef75ed8463060e018a58926bdb55

test:
  secret_key_base: 7c7aa524ba9c5a32ffa14cfd24122c775a9018e77949426e201ff7b56cacb2d1e66ec9e3db3a47f868263c24f76800c710714f6c684c9e441a80240bbecffeef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
